### ISSUE TITLE
double colon in host identifier

### ISSUE THREAD

**Issue by tomeragain** [hapijs/catbox-mongodb#26] opened 2017-05-06 18:02 UTC
after setting this values
uri: mongodb://username:dataBAsePassw0rd@hostname.com:3000
partition: database-name

with the intention of having as result this string connection 
mongodb://username:dataBAsePassw0rd@hostname.com:3000/database-name

after string uri replace, the string connection result is 
mongodb://username:dataBAsePassw0rd/database-name

throwing a ´double colon in host identifier´ error at connection time

**Comment by jardakotesovec** [comment] 2017-05-09 08:41
@tomeragain Thanks a lot for the report. I will be able to look into it and release update this week (Sunday latest). If you could provide PR with fix, it would be awesome and would speed up releasing the update.

**Comment by jardakotesovec** [comment] 2017-05-20 08:30
@tomeragain Hi, can't reproduce. We have unit test for your use case and when I tried your particular example I am getting correct connection string.

**Comment by tomeragain** [comment] 2017-05-22 16:52
Hello @jardakotesovec, sorry for the late response,
maybe is a compound issue due i use [Glue](https://github.com/hapijs/glue) to compose my server,
Thanks a lot for your support

**Comment by jardakotesovec** [comment] 2017-06-01 07:45
@tomeragain Closing for now as I can't reproduce. Please reopen if you have some further informations.

**Closed by jardakotesovec** 2017-06-01 07:45 UTC
Labels: bug
